### PR TITLE
Feature/composer

### PR DESCRIPTION
**Pull request by matijakovacevic**
Added a LICENCE file and a few things so the script could be easily added/integrated with composer.

Once you merge, you should tag it (following semantic versioning) and 
register on packagist.org so it can be discovered by composer

### CODE REVIEW

**Comment by antonioribeiro** [comment]
Awesome! Thank you!

**Comment by matijakovacevic** [comment]
don't forget to tag it and add to packagist!

**Comment by antonioribeiro** [comment]
All done: https://packagist.org/packages/antonioribeiro/artisan-anywhere

Also: added your name to the list of contributors in readme.

Thanks again!

**Comment by matijakovacevic** [comment]
no problem man!
great script!

**Pull request merged**
